language: perl
perl:
  - "5.26"
  - "5.28"
  - "5.30"
before_install:
  - "git config --global user.name TravisCI"
  - "git config --global github.user someone-stole-my-name"
install:
 - "cpanm --quiet --notest Dist::Zilla"
 - "dzil authordeps | xargs cpanm --quiet --notest && dzil listdeps --develop | xargs cpanm --quiet --notest"
script: "dzil test --release"
